default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dev_scrabble

test:
  <<: *default
  database: test_scrabble

production:
  <<: *default
  database: prod_scrabble
